name: npm-centrality
channels:
  - conda-forge

dependencies:
  - python=3.8
  - requests
  - beautifulsoup4
  - scipy
  - networkx
  - matplotlib
  - numpy
  - pandas
  - tqdm
  - notebook
  - black
  - isort
  - pip
  - pip:
      - PyGithub
      - pygount
      - criticality-score